MEMBER_JOINS = "{member} joins the tournament"
MEMBER_QUITS = "{member} quits the tournament"
MEMBER_BANNED = "{member} banned from tournament"
MEMBER_UNBANNED = "{member} unbanned from tournament"

PARTICIPANTS_MISSING_AND_IN_CHANNEL = "Participants missing: {n_away}\nParticipants in {channel}: {n_here}"
MEMBER_INVISIBLE = "{member} 👻"
MEMBER_MOBILE = "{member} 📱"
MEMBER_ERROR = "{member} ❌"
MEMBER_FARAWAY = "{member} **far away**"
MEMBER_BUSY = "{member} **busy playing**"
MEMBER_HERE = "{member} **already here**"

COULDNT_SUMMON_IN_CHANNEL = "E' richiesta la tua presenza in {channel} per il torneo di Among Us!\nVolevo spostarti, ma "
COULDNT_SUMMON_IN_CHANNEL_BECAUSE_MOBILE = COULDNT_SUMMON_IN_CHANNEL \
    + "ho notato sei da mobile :("
COULDNT_SUMMON_IN_CHANNEL_BECAUSE_INVISIBLE = COULDNT_SUMMON_IN_CHANNEL \
    + "ho notato sei invisibile :("
COULDNT_SUMMON_IN_CHANNEL_BECAUSE_BUSY = COULDNT_SUMMON_IN_CHANNEL \
    + "ho notato che sei impegnato a giocare :("
COULDNT_SUMMON_IN_CHANNEL_BECAUSE_FARWAY = COULDNT_SUMMON_IN_CHANNEL \
    + "non eri connesso a {guild} :("

N_PARTICIPANTS = "{n} participants:"
N_SPECTATORS = "{n} just listening:"
MUTED_CHANNEL = "Muted {channel}"
UNMUTED_CHANNEL = "Unmuted {channel}"

CMD_PREPARE = "PREPARE"
CMD_CLEAN = "CLEAN"
CMD_PROMOTE = "PROMOTE"
CMD_DEMOTE = "DEMOTE"
CMD_BRING = "BRING"
CMD_ASSIGN = "ASSIGN"
CMD_KICK = "KICK"
CMD_BAN = "BAN"
CMD_UNBAN = "UNBAN"
CMD_BROADCAST = "BROADCAST"
CMD_SUMMON = "SUMMON"
CMD_MUTE = "MUTE"
CMD_UNMUTE = "UNMUTE"
CMD_START = "START"
CMD_END = "END"
CMD_JOIN = "JOIN"
CMD_QUIT = "QUIT"
CMD_LIST = "LIST"
CMD_TERMINATE = "TERMINATE"